name: Node.js CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


